version: '3.3'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: stekenergofood/foodgram_backend:latest
    restart: always
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: stekenergofood/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/var/html/media/
    depends_on:
      - backend
